name: Firebase preview

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

  # Triggers the workflow after "Tests" workflow has completed
  workflow_run:
    workflows: ["Tests"]
    types: [completed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    environment: dev
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      # - uses: ahmadnassri/action-workflow-run-wait@v1 # wait for all workflow_run workflows to be successful
      - run: yarn && yarn build
        env:
          REACT_APP_HALO_TOKEN_ADDRESS_KOVAN: ${{ secrets.REACT_APP_HALO_TOKEN_ADDRESS_KOVAN }}
          REACT_APP_HALO_REWARDS_ADDRESS_KOVAN: ${{ secrets.REACT_APP_HALO_REWARDS_ADDRESS_KOVAN }}
          REACT_APP_BALANCER_POOL_URL: ${{ secrets.REACT_APP_BALANCER_POOL_URL }}
          REACT_APP_BALANCER_SUBGRAPH_URL: ${{ secrets.REACT_APP_BALANCER_SUBGRAPH_URL }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HALO_DEV_EB31C }}'
          projectId: halo-dev-eb31c
          target: app
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
